### ISSUE TITLE
User is undefined

### ISSUE THREAD

**Issue by karlbohlmark** [AzureADSamples/WebAPI-Nodejs#7]
https://github.com/AzureADSamples/WebAPI-Nodejs/blob/master/node-server/server.js#L372
```
User.findOrCreate
```
I'm guessing `User` should be a Mongoose model, but it is not defined.

**Comment by brandwe** [comment]
Actually I use in memory cache for this. It's left as an exercise to the reader to implement that storage in mongodb.
