### ISSUE TITLE
Sample needs improvement

### ISSUE THREAD

**Issue by mkliu** [AzureADSamples/WebAPI-Nodejs#9]
It shows some basics for a great start, but really needs some improvement for a smooth start. After some struggle I managed to make it work now, but blocked at the call back URL. A couple of issues:
1. It's complaining  Invalid client secret is provided at WebAPI-Nodejs/node_modules/passport-oauth/node_modules/passport-oauth2/lib/strategy.js:298:12
2. Even if #1 works, looks like it won't go back to the page i requested. And seems quite some methods will simply throw exception.

Hope this could be improved.

**Comment by brandwe** [comment]
Thanks @mkliu will do so! I'm working on it now.

**Comment by brandwe** [comment]
Updated the sample and it seems to work for me. Please check again and let me know!
